### ISSUE TITLE
Missing ships: The Void Sprites

### ISSUE THREAD

**Issue by Zitchas** [7even/endless-ships#4]
Greetings! I just noticed that the Void Sprites are missing from the ship list. Is this intentional?

Would it be possible to have them included, with a checkbox to show/hide them like with the other factions?

Thanks!

**Comment by 7even** [comment]
I think it happened because I failed to determine the faction of this ship (as I never encountered the ship in the game).

Only ships from [these](https://github.com/7even/endless-ships/blob/32271afbe80130c21ce7f0a6e50d175191e07936/src/endless_ships/core.clj#L11-L21) files are currently being rendered in the list. Unfortunately there seems to be no other way to render the faction info in the ships table so if there are ships absent from the list please send me the filename and the faction name.

**Comment by Zitchas** [comment]
They are only found in Nenia, in the Ember Waste, and as of 0.9.8, were only referred to in a single mission chain for the Remnant. At this point (0.9.11) there's three mission chains that take place in and around, and involve the Void Sprites, and I have more that are on track to being merged in 0.9.13. 

That being said, I'll keep this in mind - if/when new races/factions of ships get added, I can submit additional PRs for them. Assuming that PR #8 was done correctly, anyway. 

As a side note, I don't know if it affects your code or not, but in the past couple days the data folders for ES acquired sub-directories. So remnant ships.txt is in the remnant folder, hai ships.txt is in the hai folder, etc. (all of these folders continue to reside in the data folder, so that much hasn't changed.)

**Comment by 7even** [comment]
It is released now both to http://endless-sky.7vn.io/ and http://dev.endless-sky.7vn.io/.

> As a side note, I don't know if it affects your code or not, but in the past couple days the data folders for ES acquired sub-directories. So remnant ships.txt is in the remnant folder, hai ships.txt is in the hai folder, etc. (all of these folders continue to reside in the data folder, so that much hasn't changed.)

It's okay, this doesn't break anything.
